### ISSUE TITLE
extended argument not honored

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#106]

**Comment by tmakatos** [comment]
Turns out that this is a good ooportunity to allow the user to specify the device type: PCI/PCI-X/PCIe.

**Comment by tmakatos** [comment]
Duplicate of https://github.com/nutanix/libvfio-user/issues/13.

**Comment by jlevon** [comment]
Any thoughts on capabilities? I was looking at re-jigging that API.

**Comment by tmakatos** [comment]
I haven't looked at that yet, is there something specific you have in mind?

**Comment by jlevon** [comment]
no, not particularly
