### ISSUE TITLE
implement vfio-user functions for client usage

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#130]
@changpe1 's vfio-user implementation (https://review.spdk.io/gerrit/c/spdk/spdk/+/3839/55/lib/vfio_user/vfio_user.c and https://review.spdk.io/gerrit/c/spdk/spdk/+/3839/55/lib/vfio_user/vfio_user_pci.c.) might be a good place to start, combined with our client/server sample. We can certainly provide simple functions that do the job, but we need to put things into perspective and see how such functions would be used in more complex environments, e.g. where file descriptors are in non-blocking mode etc.

**Comment by jlevon** [comment]
I don't think this is a useful thing for us to do due to the disparate circumstances clients need to operate in, not the least, which language.
