### ISSUE TITLE
vfio-user protocol doesn't define how to handle failures when adding multiple DMA regions

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#131]
If the server fails to add multiple DMA region it cannot communicate to the client which regions where added and which failed. The client will receive a single error response informing it of the failure, however it's impossible for it to tell which regions were added and which weren't, so the only reliable way to clean up is for the client to attempt to unmap all regions, ignoring failures in the mean time.

Possible ways to solve this:

1. Expect the client to clean up. That seems as the simplest one.
2. The server must either completely succeed or completely fail: if adding a DMA region fails then it must remove all other DMA regions in the request.
3. Add a bitmap in the response indicating which regions succeeded and which failed.

I think the easiest to do is option 1. We simply have to document it in the protocol specification. We can also implement the other two options later without breaking the protocol by introducing appropriate capabilities.

@jlevon @swapnili thoughts?

**Comment by swapnili** [comment]
I think (2) is better options. Either all succeeded or none, its better server should not expect client to callback for the cleanup which could have been done previously. This will also keep the protocol simple.

**Comment by tmakatos** [comment]
I've explained in the protocol that adding multiple DMA regions can partially fail therefore it's up to the client how to handle it. This is good enough for now. Leaving the issue open since it can be further improived.

**Comment by tmakatos** [comment]
This is no longer relevant because of #502
