### ISSUE TITLE
re-work PCI config hdr API

### ISSUE THREAD

**Issue by jlevon** [nutanix/libvfio-user#143]
Currently, we have an API that allows setting some PCI header register values, and a separate API to allow adding some capabilities.

Instead, we should just take the entire PCI config header as an argument.
We could provide helpers to initialize its contents (including adding caps).

We might also want to look at having a read/write callback for API users to optionally implement. Not sure how that would interact with our handled caps etc.

Also unclear is extended config space.

**Comment by tmakatos** [comment]
My concern is that we might end up complicating things for the user. The user should not be exposed to configuration parameters that the libary can handle internally. Making a device implementation as easy as possible is one of the key strenghts of libvfio-user. What problem our we trying to solve by reworking the API?

Regarding _vendor_ capabilities, we should definitely allow callbacks.

**Comment by jlevon** [comment]
done now
