### ISSUE TITLE
consider simplifying logging to avoid having to pass lm_ctx around

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#16]

**Comment by tmakatos** [comment]
@franciozzy thoughts about this?

**Comment by franciozzy** [comment]
The logging function is per-context, so the context is needed whenever logging is needed. If we are having to pass the context around _just_ for logging, I'd argue we need to review how (and where) the context is being kept to avoid that. That is not the same as "simplify logging", though.

**Comment by jlevon** [comment]
We pass the context back into the log callback for the benefit of consumers now, so this is no longer relevant.
