### ISSUE TITLE
Compilation error with Ubuntu16.04 and clang-9

### ISSUE THREAD

**Issue by changpe1** [nutanix/libvfio-user#205]
There are two compilation errors here:
The first one is Ubuntu16.04 doesn't have PCI_CFG_SPACE_SIZE definition in linux/pci_regs.h header file, libvfio-user may add this define if the macro wasn't defined.

The other one is for clang:

 Building C object samples/CMakeFiles/client.dir/__/lib/tran_sock.c.o
00:04:20.610  /home/vagrant/spdk_repo/spdk/libvfio-user/samples/client.c:159:33: error: format specifies type 'unsigned short' but the argument has type 'int' [-Werror,-Wformat]
00:04:20.610                 sversion->major, LIB_VFIO_USER_MAJOR);
00:04:20.610                                  ^~~~~~~~~~~~~~~~~~~
00:04:20.610  /home/vagrant/spdk_repo/spdk/libvfio-user/include/libvfio-user.h:57:29: note: expanded from macro 'LIB_VFIO_USER_MAJOR'
00:04:20.610  #define LIB_VFIO_USER_MAJOR 0
00:04:20.610                              ^
00:04:20.610  /home/vagrant/spdk_repo/spdk/libvfio-user/samples/client.c:167:33: error: format specifies type 'unsigned short' but the argument has type 'int' [-Werror,-Wformat]
00:04:20.610                 sversion->minor, LIB_VFIO_USER_MINOR);
00:04:20.610                                  ^~~~~~~~~~~~~~~~~~~
00:04:20.610  /home/vagrant/spdk_repo/spdk/libvfio-user/include/libvfio-user.h:58:29: note: expanded from macro 'LIB_VFIO_USER_MINOR'
00:04:20.610  #define LIB_VFIO_USER_MINOR 1
00:04:20.610                              ^
00:04:20.614  /home/vagrant/spdk_repo/spdk/libvfio-user/samples/client.c:420:14: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
00:04:20.614          char data[data_len];
00:04:20.614               ^
00:04:20.614  /home/vagrant/spdk_repo/spdk/libvfio-user/samples/client.c:419:40: error: field 'region_access' with variable sized type 'struct vfio_user_region_access' not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end]
00:04:20.614          struct vfio_user_region_access region_access;
00:04:20.614                                         ^
00:04:20.623  4 errors generated.
00:04:20.629  make[5]: *** [samples/CMakeFiles/client.dir/build.make:83: samples/CMakeFiles/client.dir/client.c.o] Error 1
00:04:20.629  make[5]: *** Waiting for unfinished jobs....
00:04:20.668  make[4]: *** [CMakeFiles/Makefile2:686: samples/CMakeFiles/client.dir/all] Error 2
00:04:20.669  make[3]: *** [Makefile:150: all] Error 2
00:04:20.669  make[2]: *** [Makefile:55: all] Error 2
00:04:20.670  make[1]: *** [Makefile:48: all] Error 2
00:04:20.670  make: *** [/home/vagrant/spdk_repo/spdk/mk/spdk.subdirs.mk:44: vfiouserbuild] Error 2
00:04:20.670  make: *** Waiting for unfinished jobs....
00:04:34.303  clang-9: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]

**Comment by tmakatos** [comment]
Ubuntu 16 is EOL end of April 2021, I don't think it's worth fixing it.

**Comment by jlevon** [comment]
I forgot to mention here, but clang build is fixed and in CI
