### ISSUE TITLE
install the static libvfio-user.a file in the install directory

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#236]
@changpe1 would like this, I think we should  do it but only for debug builds

**Comment by jlevon** [comment]
Blocked until we understand why @changpe1 wants this.

**Comment by changpe1** [comment]
@jlevon SPDK uses static library but the include header file is in the install directory.

**Comment by jlevon** [comment]
We should just do this for the benefit of SPDK build

**Comment by jlevon** [comment]
Fixed by #267
