### ISSUE TITLE
entirely mappable migration region must not allow struct vfio_device_migration_info to be mmaped

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#287]
The user requests migration support for the device and in reponse we initialize the migration region. The migration region we create is `sizeof(struct vfio_device_migration_info)` bytes larger than the user requested in order to fit at the beginning of it the migration registers `struct vfio_device_migration_info`. If the user specifies the entire migration region to be mappable (by providing a file descriptor but setting `mmap_areas` to NULL), we need to internally make the migration region sparsely memory mappable, excluding the migration registers at the beginning.

**Comment by tmakatos** [comment]
Check `init_migration`.

**Comment by tmakatos** [comment]
The user requests migration support for the device and in reponse we initialize the migration region. The migration region we create is `sizeof(struct vfio_device_migration_info)` bytes larger than the user requested in order to fit at the beginning of it the migration registers `struct vfio_device_migration_info`. If the user specifies the entire migration region to be mappable (by providing a file descriptor but setting `mmap_areas` to NULL), we need to internally make the migration region sparsely memory mappable, excluding the migration registers at the beginning.

**Comment by tmakatos** [comment]
The original problem in this issue is easily fixed. However, I discovered the following problem when the migration region is memory mappable (either wholly or in part via sparse mmaps): the user supplies a file descriptor with the sparse mmap addresses based on the beginning of the file. However, libvfio-user will create a PCI region which must be `sizeof(struct vfio_device_migration_info)` larger than the migration region the user specifies in order to contain the migration registers. The migration registers must be placed at the beginning of the migration region and cannot be memory mapped. The problem is that we cannot simply adjust the base addresses of the sparse mmaps by adding `sizeof struct vfio_device_migration_info` because that would require changing the size of the file and shifting the first few bytes. If we leave the sparse mmaps to their original values then they'll be wrong. This whole problem stems from our decision to hide the fact that migration is implemented as a PCI region. One way to solve this problem is to have libvfio-user create the file and return the file descriptor to the user, or have the user supply the file descriptor but leave to the library to truncate it accordingly and return the usable area. Another way to solve this is to tell the user to reserve a few extra bytes at the beginning of the file (we can implement a function to return `sizeof struct vfio_device_migration_info`. Or we can simply expose the fact that migration is implemented as a region. @jlevon @swapnili thoughts?

**Comment by tmakatos** [comment]
I think a reasonable comprosie to the above problem is to request that the file should contain some initial empty space of at least `sizeof struct vfio_device_migration_info` bytes and this area must not be accessed.

**Comment by tmakatos** [comment]
Another possibly better approach would be to have libvfio-user create the file and mmap it, and provide a pointer to the part of the file excluding `struct vfio_device_migration_info` at the beginning. The user doesn't have to know that this memory is backed by a file or that there's stuff before that address.

**Comment by swapnili** [comment]
I think better approach is libvfio-user creates and setups the file, user do not have to know about this fact and can just use the memory returned back by libvfio-user.

**Comment by tmakatos** [comment]
After discussing the issue with @jlevon and @swapnili we decide to expose the fact that live migration is done via a region. We'll document that the user needs to reserve at least `sizeof(struct vfio_device_migration_info)` bytes at the beginning of the migration region. We'll keep the callbacks but make them optional: if the user doesn't procide callbacks then the standard region read/write callbacks will be called and the user must handle accesses to the migration region registers. The only remaining question is whether we should fix the migration region index right after the PCI ones or make it freely selectable, as VFIO allows it. We should reach out to the VFIO maintainers for clarification.
