### ISSUE TITLE
make migration callbacks optionally asynchronous

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#296]

**Comment by jlevon** [comment]
Do you think it's painful to change them such they're always async? Or does that get nasty for a non-async user?

**Comment by tmakatos** [comment]
> Do you think it's painful to change them such they're always async? Or does that get nasty for a non-async user?

I think it would be too painful, but it's an option. Here are some options:

1. The user defines per context or per region or per sub-region behavior via a new flag. This flag tells libvfio-user whether it must send a response after the user's region callabck has returned or do so when the user explicitly notifies completion via a new callback.
2. The user's region callback returns, along with the error code, whether or not libvfio-user must immediatelly send a response.
3. Make it always asynchronous, as @jlevon suggested.

Thoughts?

**Comment by tmakatos** [comment]
Irrespectively of the high level behavior we choose, we need to move all variables into a dynamically-allocated struct (the request context) so that we can send the response at a later time. We also need to consider whether we need locks for writing to the socket, since the user of thel library might be completing requests from multiple threads. We also need to consider what the behavior of the library should be when there is a pending request and another, potentially conflicting request arrives: e.g. what happens when the device is being set to a particular migration state and in the mean time a write to a BAR arrives?

I think for now we can allow only the migration region to be accessesed asynchronously. When this happens we can set a flag that makes `process_request` immediatelly return that there is no work to be done, without checking the socket. This can only work with `LIBVFIO_USER_FLAG_ATTACH_NB`.

**Comment by tmakatos** [comment]
Pausing for now, WIP stashed in https://github.com/nutanix/libvfio-user/tree/tmakatos/issues/296.

**Comment by tmakatos** [comment]
In https://review.spdk.io/gerrit/c/spdk/spdk/+/7617 it became evident that highly asynchronous applications such as SPDK will have a very hard time supporting live migration. We should re-prioritize implementing this.

**Comment by tmakatos** [comment]
The simplest way to make the migration state callback asynchronous is for the caller to indicate e.g. via a return value whether or not the transition occured. If it did occur then it's no different from the current implementation. If it didn't occur we record the fact that there is a migration state pending (e.g. introduce a bit in the libvfio-user context) and then we don't process anything (`vfu_run_ctx()` should check whether the bit is set and if so it should return -1 and set `errno` to `EAGAIN`) until the user tells libvfio-user that migration state transition finished. We can implement a similar solution for making DMA map/unmap asynchronous.
