### ISSUE TITLE
which branch of qumu can run gpio demo of current  libvfio-user?

### ISSUE THREAD

**Issue by kkndyu** [nutanix/libvfio-user#368]
Hi there,

when I used the oracle/qemu vfio-user-v0.6 branch, error log like:

gpio: closing unexpected fd 5 (index 0) from cmd 2
gpio: closing unexpected fd 5 (index 0) from cmd 2
gpio: msg0x6: cmd 4 failed: Invalid argument
gpio: vfio-user client closed connection

qemu-system-x86_64: -device vfio-user-pci,socket=/tmp/vfio-user.sock: vfio VFIO user </tmp/vfio-user.sock>: get info failure: Invalid argument

when I used the jlevon/qemu vfio-user-fixes.1 branch, error log like:

gpio: vfio-user client closed connection

qemu-system-x86_64: -device vfio-user-pci,socket=/tmp/vfio-user.sock: vfio_user_recv msg=0 cmd=0 reply (100) larger than recv buffer (85)
qemu-system-x86_64: -device vfio-user-pci,socket=/tmp/vfio-user.sock: vfio_user_recv short read of msg body
qemu-system-x86_64: -device vfio-user-pci,socket=/tmp/vfio-user.sock: vfio (null): version reply: Invalid argument

so  which qemu branch can paired with the gpio demo of currentlibvfio-user?

Thanks,
Eric

**Comment by tmakatos** [comment]
This is the only one that works for now: https://github.com/tmakatos/qemu-oracle/commits/vfio-user-v0.6

Let me know if it doesn't work for you.

**Comment by kkndyu** [comment]
great, with this branch I can see the gpio device in vm now

00:04.0 Non-VGA unclassified device: ACCES I/O Products, Inc. PCI-IDIO-16 Isolated Digital Input / FET Output Card

Thanks a lot.

**Comment by tmakatos** [comment]
This shouldn't have been closed (#739 fixes it).
