### ISSUE TITLE
[muser]is it OK to use userspace pointer in kernel direcly

### ISSUE THREAD

**Issue by kkndyu** [nutanix/libvfio-user#383]
I used the Debian 4.19 kernel to test the kmod, all seems OK except the function in muser.c

void dump_buffer(unsigned char const *const buf, uint32_t count)

I can see call trace of kernel like : BUG: unable to handle kernel paging request at ...

the "buf" is a userspace pointer, should it be used after call copy_from_user?

**Comment by tmakatos** [comment]
Yes I think you're right, it needs to be movde after `copy_from_user`, not sure why this didn't trigger for us in the first place. Feel free to raise a PR if you have a patch that fixes it.

Bear in mind that the kernel module is no longer maintained. Doesn't the purely user space version work for your use case?

**Comment by kkndyu** [comment]
Hi tmakatos,

I'm still estimating these frameworks, actually I want to emulate a simple pcie switch and static link/hotplug some endpoints behind it. 

any suggestions?

**Comment by tmakatos** [comment]
> I'm still estimating these frameworks, actually I want to emulate a simple pcie switch and static link/hotplug some endpoints behind it.

Isn't the purely user space solution implemented in the master branch suitable for this?

**Comment by jlevon** [comment]
Just a heads-up, so far our focus has been on endpoints, further work in the framework would probably be necessary to emulate a switch.

**Comment by jlevon** [comment]
Hi @kkndyu I'm going to close this ticket shortly, the old kernel muser branch isn't maintained, and it's not something we plan to work on any more.

If you hit issues with the userspace libvfio-user, please do file bugs / feature requests. Thanks.

**Comment by tmakatos** [comment]
Just to add that we'd welcome contributions to the kernel module if there is a valid use case.

**Comment by jlevon** [comment]
closing as per above
