### ISSUE TITLE
Sparse mmap support for Live Migration region

### ISSUE THREAD

**Issue by changpe1** [nutanix/libvfio-user#440]
Existing APIs can't tell the backend how many bytes are read from QEMU for the live migration region is enabled with sparse mmap.

One workaround from me is that:
1. if the device state is in SAVING state
2. return pending_bytes with whole device state bytes
The QEMU will read pending_bytes again and again, so we can return the correct value after several times.

A better idea maybe required from QEMU side or libvfio-user.

**Comment by tmakatos** [comment]
> Existing APIs can't tell the backend how many bytes are read from QEMU for the live migration region is enabled with sparse mmap.

I'm not sure I understand what the problem is. `get_pending_bytes` gets called when QEMU has consumed the migration data, even when sparse mmap is enabled. Doesn't this happen in your case?

**Comment by changpe1** [comment]
In the VFIO_DEVICE_STATE_SAVING state, the QEMU will do the following actions:

while (pending_bytes > 0) {
    1. read migration data_offset value via MMIO
    2. read migration data_size value via MMIO
    3. read sparse mmap region with "data_size"
    4. update pending_bytes value via MMIO
}
step 1 and step 2 are responded via "prepare_data" callback in libvfio-user
step 4 is responded via "get_pending_bytes" callback in libvfio-user

Let's say the size of device state is 0x7000, so for the first round call:
1. data_offset is 0x1000, data_size is 0x7000, pending_bytes is 0x7000,
then for the second round call:
1.  data_offset is 0x8000, data_size is 0x0, pending_bytes is 0x0

I used the above implementation which passed the live migration process with QEMU.

**Comment by changpe1** [comment]
For non-sparse memory regions, the backend can actually know the read offset of the migration region, this means extra one acknowledge from QEMU compared with sparse mmap case, so for sparse mmap case, the backend actually don't know how many bytes are really read from QEMU.

**Comment by tmakatos** [comment]
Let me take a step back. 

> Existing APIs can't tell the backend how many bytes are read from QEMU for the live migration region is enabled with sparse mmap.

When sparse mmap is used, it is impossible to know exactly how many bytes QEMU has read since it's reading memory. The VFIO migration protocol is designed in a way that is agnostic to whether or not the migration data are mappable. Rather than introducing special handling logic, treating both cases the same simplifies the implementation. Can you elaborate what the problem is in your case? Is migration performance slow? Are you looking at optimizing this?

**Comment by changpe1** [comment]
Yeah, I'm looking an optimization for sparse mmap, as I said at the beginning, a better idea in QEMU or libvfio-user.  

I didn't meet any issues when doing live migration, just think that the existing messages are not friendly and reasonable for sparse mmap.

**Comment by tmakatos** [comment]
So in the sequence of steps you wrote:
```
while (pending_bytes > 0) {
    1. read migration data_offset value via MMIO
    2. read migration data_size value via MMIO
    3. read sparse mmap region with "data_size"
    4. update pending_bytes value via MMIO
}
```
Are you saying that step 4 could be avoided if the migration region is not sparsely mappable?

**Comment by changpe1** [comment]
> So in the sequence of steps you wrote:
> 
> ```
> while (pending_bytes > 0) {
>     1. read migration data_offset value via MMIO
>     2. read migration data_size value via MMIO
>     3. read sparse mmap region with "data_size"
>     4. update pending_bytes value via MMIO
> }
> ```
> 
> Are you saying that step 4 could be avoided if the migration region is not sparsely mappable?

No, I only talked about the sparsely mappable case here.

step 3 is the only difference between sparse mmap region and mmio access.

**Comment by tmakatos** [comment]
I still don't understand what the issue is. Are you looking for a way to notify the backend, when the migration region is mappable, that some migration data have been read before the `get_pending_bytes` callback is called?

**Comment by changpe1** [comment]
> I still don't understand what the issue is. Are you looking for a way to notify the backend, when the migration region is mappable, that some migration data have been read before the `get_pending_bytes` callback is called?

exactly.

**Comment by tmakatos** [comment]
I don't think this is possible. First of all, there's no way to tell which parts of the migration region QEMU reads since this it's shared memory. Also, changing QEMU to notify libvfio-user when it has read some part of the migration data requires changing the base VFIO implementation as well, which I'm not sure how desirable it will be. I'm not saying that it can't be done, I'm saying that it's probably not worth the effort.

**Comment by changpe1** [comment]
> I don't think this is possible. First of all, there's no way to tell which parts of the migration region QEMU reads since this it's shared memory. Also, changing QEMU to notify libvfio-user when it has read some part of the migration data requires changing the base VFIO implementation as well, which I'm not sure how desirable it will be. I'm not saying that it can't be done, I'm saying that it's probably not worth the effort.

OK, I'm closing this issue now.
