### ISSUE TITLE
spec issue: revisit partial removal of DMA portion

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#481]
> > > > "Removing a portion of a DMA region is possible"
> > > -> doing so splits a larger DMA region into one or two smaller 
> > > -> remaining
> > regions?
>> 
> > We certainly don't have that implemented. Thanos?
>
> Correct, removing a portion of a DMA region could result in two regions.
Indeed, this isn't currently implemented. We wanted to leave the door open to such behavior if we wanted it in the future. Now I'm thinking that maybe we should put this behind an optional capability.

**Comment by tmakatos** [comment]
On second thought, I think the spec should allow for removing a portion of a DMA region. We don't have to support it in libvfio-user yet, since we don't have a valid use case. If we allow it in the future then the client might be unneccessarily complicated with having to handle the case where the server doesn't support partial removal. @jlevon thoughts?

**Comment by jlevon** [comment]
Accidentally opened #504 as a dupe, but closing this one
