### ISSUE TITLE
spec issue: describe in/out parameters

### ISSUE THREAD

**Issue by jlevon** [nutanix/libvfio-user#486]
```
> Is count an output-only field since the previous sentence says index is
> the only field required in the command message?
> 
> I find it confusing that the spec shows the input/output structs without
> explicitly documenting that fields are input, output, or input & output.
```

**Comment by john-johnson-git** [comment]
I think it might be a good idea to document the request and reply message formats in different tables.  In hindsight, I should've done that at the beginning.

**Comment by tmakatos** [comment]
@jlevon the existing section of VFIO_USER_DMA_UNMAP is wrong, it needs rewriting (https://github.com/nutanix/libvfio-user/issues/4800, so you can skip it when describing in/out fields.

**Comment by jlevon** [comment]
done now
