### ISSUE TITLE
spec issue: VM_INTERRUPT doesn't identify IRQ type

### ISSUE THREAD

**Issue by jlevon** [nutanix/libvfio-user#487]
+VFIO_USER_VM_INTERRUPT via Stefan:

```
> Hmm...this is weird. The server tells the client to raise an MSI-X
> interrupt but does not include the MSI message that resides in the MSI-X
> table BAR device region? Or should MSI-X interrupts be delivered to the
> client via VFIO_USER_DMA_WRITE instead?
```

cf #387

**Comment by tmakatos** [comment]
I don't know enough about MSI-X to come up with a trigger mechanism. Since this can be done via DMA write, can we go with this option for now? @jlevon ?

**Comment by jlevon** [comment]
I'm removing this altogether for now anyway

**Comment by jlevon** [comment]
Fixed by removing the message
