### ISSUE TITLE
spec issue: partial unmap expectations?

### ISSUE THREAD

**Issue by jlevon** [nutanix/libvfio-user#504]
Alex Williamson:

```
> > +* *Address* is the base DMA address of the region.
> > +* *Size* is the size of the region.
> 
> Are there any assumptions about address and size of the unmap command
> relative to the original map command or is the client freely allowed to
> bisect, overlap, or overextend previous mappings?
```

**Comment by jlevon** [comment]
And also

```
> How might we indicate unmap granularity must match
> mapping granularity restrictions to the user in the future should some
> acceleration technology require it?  This is akin to the TYPE1 vs
> TYPE1v2 distinction in the kernel.
```

**Comment by tmakatos** [comment]
#481 is relevant.

> Are there any assumptions about address and size of the unmap command
> relative to the original map command or is the client freely allowed to
> bisect, overlap, or overextend previous mappings?
> ...
> How might we indicate unmap granularity must match
> mapping granularity restrictions to the user in the future should some
> acceleration technology require it?  This is akin to the TYPE1 vs
> TYPE1v2 distinction in the kernel.

Initially the assumptions were that the client can arbitrarily unmap any part of an existing mapping. However, I don't think thatthe server must necessarily support such functionlaity. Therefore, I propose to change the spec to enforce strict unmap granularity by default and allow this requirement to be relaxed by introducing the appropriate capabilities in the future.

**Comment by tmakatos** [comment]
@jlevon thoughts?

**Comment by jlevon** [comment]
let's be strict, yep
