### ISSUE TITLE
lspci shows FLR not supported 

### ISSUE THREAD

**Issue by swapnili** [nutanix/libvfio-user#524]
Even if FLRC is set lspci shows it is not supported,

Capabilities: [48] Express (v2) Endpoint, MSI 00
	DevCap:	MaxPayload 128 bytes, PhantFunc 0, Latency L0s <64ns, L1 <1us
	ExtTag- AttnBtn+ AttnInd- PwrInd- RBE- FLReset- SlotPowerLimit 128.000W

**Comment by jlevon** [comment]
It's not just lspci, the linux kernel agrees (no reset callback in sysfs)
