### ISSUE TITLE
dirty page logging: VFIO_USER_DIRTY_PAGES must clear dirty page bitmap

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#526]
I believe it should, however I'm looking at `VFIO_IOMMU_DIRTY_PAGES` and it's not clear.

**Comment by jlevon** [comment]
For my own benefit here:

The problem is that if we don't clear, then the relevant pages (and it's the entire sg's, ever used) will always be dirty, most likely making the downtime include all those pages.

**Comment by tmakatos** [comment]
I'm looking at `vfio_iommu_type1_dirty_pages` and my understanding is that all currently pinned pages are considered dirty (` vfio_iova_dirty_bitmap`) and that they remain dirty after `vfio_iommu_type1_dirty_pages` returns.

**Comment by tmakatos** [comment]
Closing since it's tightly coupled with https://github.com/nutanix/libvfio-user/issues/540.
