### ISSUE TITLE
make pytest succeeds even if python-3-pytest is not installed

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#542]
We should at least print that no tests have been run because python-3-pytest is not installed.

**Comment by jlevon** [comment]
This is so we don't require Python when actually being used.

As we test in our CI, I don't think this is a big deal or worth fixing.

**Comment by tmakatos** [comment]
I implemented a unit test and as I didn't have pytest installed it didn't do anything, wouldn't a warning be a reasonable compromise?

**Comment by jlevon** [comment]
If you like, though I feel it'd be pretty lost in the noise of make test, and you'd find out when pushing to the PR branch anyway.
