### ISSUE TITLE
spec issue: DMA_MAP MAPPABLE flag

### ISSUE THREAD

**Issue by jlevon** [nutanix/libvfio-user#552]
The MAPPABLE flag in 'flags' field of the DMA_MAP struct is vfio-user-specific, but currently we sort of re-use the VFIO flags.

Instead, now we accept only one map at a time, we can drop the flag and presume that if an fd is provided, it's mappable, and vice versa.

**Comment by tmakatos** [comment]
JJ pushed the fix here: https://github.com/oracle/qemu/commit/9baf27a8fb99392a4ff85071670cd40cec1ef4af

Need to adapt libvfio-user and test.

**Comment by tmakatos** [comment]
Fixed by #553
