### ISSUE TITLE
consider using LOG_XXX defines from syslog(3)

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#57]
We can avoid defining LM_ERR/INF/DBG by using LOG_ERR etc, provided by `<syslog.h>`.

**Comment by tmakatos** [comment]
Currently we require the the user to specify a log function. Typically the user will implement a log function that writes to a file. This can be useful for redirecting log messages to a single place that contains messages for a particular VM from other processes. However, logging to a file can block because the file system might be busy. I propose to allow the current behavior (assuming that the user knows what they're doing), but discourage it by providing a default implementaton for the log function that is automatically used if the user doesn't provide one. This function should log using syslog(3) and the log message should be prefixed with some ID provided by the user (this can be the socket path or some new string the user provides when `lm_ctx` is creared). We can also drop our custom `LM_ERR/INF/DBG` defines and switch to the ones provided from syslog(3).

@jlevon @swapnili thoughts?

**Comment by jlevon** [comment]
I'm not really clear why writing to disk is a problem: we shouldn't be generating logs in the fast path anyway (except for when debug's enabled, in which case it doesn't matter). As you say syslog is a pain for separating things out.

Either way we can use syslog's defines though.

**Comment by tmakatos** [comment]
You're right in that we generally shouldn't be generating logs, however, if we run into some problem where the guest constantly sends requests that fail, we'll be logging. If this happens then we'll end up logging to the disk, and this can block. I've learned this the hard way.

**Comment by jlevon** [comment]
We can't let an untrusted client create arbitrary amounts of logging anyway (we might want an explicit function for that, not sure). But I take your point.

How about we default to stdout/stderr - this can actually be the right choice in many circumstances. We'll provide a way to use syslog instead, or the user can specify their own logger too as you mention.

**Comment by tmakatos** [comment]
Logging to stdout/stderr by default sounds the sensible thing to do.
