### ISSUE TITLE
vfu_dma_info_t->vaddr is NULL with vfu_get_poll_fd()

### ISSUE THREAD

**Issue by jraman567** [nutanix/libvfio-user#589]
Tried to set the vfu ctx to non-blocking mode, and poll on the fds returned by vfu_get_poll_fd(). In this case, vfu_dma_info_t->vaddr is NULL/zero during the vfu_dma_register_cb_t callback.

I tried the following:
- Created vfu context with LIBVFIO_USER_FLAG_ATTACH_NB flag
- Retried vfu_attach_ctx() as long as it returned EAGAIN or EWOULDBLOCK, until it was successful
- Got the fd for the context using vfu_get_poll_fd() and set handlers for the fd using qemu_set_fd_handler()
- The handler calls vfu_run_ctx()

Noticed that vfu_dma_info_t->vaddr is zero in the vfu_dma_register_cb_t callback

**Comment by jlevon** [comment]
can you turn on DEBUG logging / vfu_setup_log for libvfio-user and provide the whole output please?

**Comment by jraman567** [comment]
Sorry, this is not an issue
