### ISSUE TITLE
vfu_map_sg() concurrency

### ISSUE THREAD

**Issue by jlevon** [nutanix/libvfio-user#594]
Currently, vfu_addr_to_sg(), vfu_map_sg() and vfu_unmap_sg() cannot be used in a concurrent manner. This is for a few reasons:

1. the (unused) region refcnt is not atomic
2. the ->maps linked list is not atomic
3. unless otherwise prevented, a concurrent `VFIO_IOMMU_DIRTY_PAGES_FLAG_GET_BITMAP` can race with dirty bitmap tracking of `vfu_map_sg()`
4. unless otherwise prevented, a concurrent `VFIO_USER_DMA_UNMAP` can race with region dereference in above calls.
5. same can happen in response to any context-using call in the case the socket client hangs up and we need to tear down the DMA controller - that will result in unmap callbacks

However SPDK would like to be able share libvfio-user context across reactors/pthreads. vfu_run_ctx can likely be pthread-protected, in the expectation there's only one poller on library state (so no contention), which leaves the above I/O handling code. Let's presume that SPDK can provide exclusion such that no active sg maps are present across a DMA unmap. The question becomes can be support multi-threaded use of the above three APIs.

1. We can remove the refcnt altogether.
2. we'd have to make the dirty bitmap writing atomic op
3. we'd have to use some lockless structure for ->maps or otherwise approach the problem
4. if a dirty pages get call comes in, that's currently not safe against a concurrent vfu_map_sg() marking things dirty

As a reminder, `->maps` exists so that if a consumer does `vfu_map_sg()` and *then* we are asked to enable dirty page tracking, we won't mark those pages as dirty, and will hence potentially lose data. Note that we actually only need that information during that transition, to catch vfu_map_sg() that happened just before dirty page tracking (and hence didn't mark dirty).

If we could ensure there were no inflight DMAs at the time of enabling dirty page tracking, we wouldn't need the map list at all.

Looking at this again, though, it looks a bit dubious anyway.

**Comment by jraman567** [comment]
I'm wondering if a `pthread_rwlock` would be a fair compromise between performance between thread-safety.

Any thread that needs to perform vfu_map_sg() with vfu_ctx could take the pthread_rwlock_rdlock() - which can be taken by multiple threads concurrently.

Any thread that wants to perform the unmap operation could consider taking the `pthread_rwlock_wrlock()` - which prevent further rdlocks from being issues and waits for existing rdlocks to be returned.

**Comment by jlevon** [comment]
a R/W lock helps a bit, certainly, but they're still not great for concurrency

Also I'm not really sure how that would even work in SPDK context since it would mean the unmap happening, and the poller going to sleep waiting for all the readers stuck in I/O land

**Comment by jlevon** [comment]
fixed a while back
