### ISSUE TITLE
mark dirty at unmap time

### ISSUE THREAD

**Issue by jlevon** [nutanix/libvfio-user#595]
It's late but isn't this a bug:

![image](https://user-images.githubusercontent.com/21101340/130109494-663b9def-a28e-45d6-9862-e9cb63e68d68.png)

and can't we fix it simply by marking dirty in `vfu_unmap_sg()` ? If so, do we even need `->maps` ?

**Comment by jlevon** [comment]
cc @tmakatos @swapnili

**Comment by swapnili** [comment]
> can't we fix it simply by marking dirty in vfu_unmap_sg() 

Isn't the dirty page tracking is required only when device implementations maps the SG to do IO on it. It is not clear to me how marking dirty in vfu_unmap_sg() will achieve this.

**Comment by jlevon** [comment]
> how marking dirty in vfu_unmap_sg() will achieve this.

By definition when the caller calls vfu_unmap_sg(), it's finished any possible writes to the mapped region.

The question is whether the final stage of live migration (downtime) can happen when there's still an active vfu_map_sg(), or will the device have finished and called vfu_unmap_sg() by that point? If so we can use unmap, and we don't have the bug above.

If that's the not the case, it seems fundamentally racy anyway.

Otherwise, presuming I'm right about the bug above, we will need the consumer to explicitly mark when a page has been written to.

**Comment by jlevon** [comment]
closing as this isn't quite correct: there's no bug today because after clearing the bitmap, we immediately mark dirty all extant maps again
