### ISSUE TITLE
Use SPDK-NVMe as VFIO user device with QEMU

### ISSUE THREAD

**Issue by likebreath** [nutanix/libvfio-user#625]
I wonder what's the best setup to test NVMf/vfio-user with QEMU? The context is that I would like to get a reference for the VFIO user support in Cloud Hypervisor.

I tried the following setup:

* QEMU: https://github.com/oracle/qemu/tree/vfio-user-rfc3 (latest branch I can find)
* NVMf/vfio-user in SPDK: https://github.com/spdk/spdk/commit/0814f8662a5f18d5bdabfcb2d299b0bc9f40e726 (upstream)
* NVMf/vfio-user was setup based on the [vfio-user.md](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/vfio-user.md#example-nvme-device) from Cloud Hypervisor. 
* QEMU was launched with `-device vfio-user-pci,socket=/tmp/test-vfio-user/nvme-vfio-user/cntrl`.

In this way, I encountered an error reported from QEMU: 
```
qemu-system-x86_64: -device vfio-user-pci,socket=/tmp/test-vfio-user/nvme-vfio-user/cntrl: vfio VFIO user </tmp/test-vfio-user/nvme-vfio-user/cntrl>: failed to get region 0 info: Invalid argument
```

I also tried the gpio device (https://github.com/nutanix/libvfio-user#gpio), and it works fine for qemu.

**Comment by likebreath** [comment]
Considering the `vfio-user` is sitting in the center of the related projects, I hope I find the right place to ask this question. Thank you for the help.

**Comment by jlevon** [comment]
A (backport of) https://github.com/oracle/qemu/tree/vfio-user-v0.93 is what we are using. It's probably best to ask on libvfio-user slack, as Oracle are there too.
Anything in spdk/libvfio-user logs (presuming you compiled with debug) ?

**Comment by swapnili** [comment]
> qemu-system-x86_64: -device vfio-user-pci,socket=/tmp/test-vfio-user/nvme-vfio-user/cntrl: vfio VFIO user </tmp/test-vfio-user/nvme-vfio-user/cntrl>: failed to get region 0 info: Invalid argument
This should already be fixed by https://github.com/nutanix/libvfio-user/pull/619

Can you retry with latest libvfio-user master? It should be a submodule in spdk repo

**Comment by likebreath** [comment]
@jlevon Great to know. I will switch to the qemu branch you are using. Would you also please send a invite the libvfio-user slack channel to me (chen.bo@intel.com)?

@swapnili Great input. Let me double check the libvfio-user submodule of spdk.

Thank you all for the prompt response.

**Comment by likebreath** [comment]
My issue was resolved by switching to https://github.com/oracle/qemu/tree/vfio-user-v0.93 and manually upgrade libvfio-user submodule to its latest within SPDK (also need to enable shared memory for qemu guest RAM). Thank you all for the prompt response and help.
