### ISSUE TITLE
use CMake's build type instead of "dbg"

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#639]
We use "dbg" for debug build but expect "Release" for release builds:
https://github.com/nutanix/libvfio-user/blob/314ed91fd991756bef2c87ecdf7feff4016c1d40/Makefile#L31

Let's be consistent and use CMake's values.

**Comment by jlevon** [comment]
will become irrelevant when we move to meson

**Comment by tmakatos** [comment]
superseded by #666
