### ISSUE TITLE
test Oracle's vfio-user client with libvfio-user

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#71]

**Comment by jlevon** [comment]
Current status: the qemu code never receives the response to the initial VFIO_USER_VERSION. Seems to be an issue with assumptions over fd callback handling in qemu, so we're blocked on that getting sorted.

**Comment by jlevon** [comment]
Current status: with my PR against oracle qemu, current libvfio-user master works with the gpio server

**Comment by tmakatos** [comment]
Using @jlevon 's PR, Oracle QEMU doesn't handle region capabilities, see https://libvfio-user.slack.com/archives/C01AFGCSPTR/p1607598616185900 for more details.

**Comment by tmakatos** [comment]
BAR4 and BAR5 have been removed from SPDK, they're used for MSI-X, I fixed that, see https://libvfio-user.slack.com/archives/C01AFGCSPTR/p1607614872190000 for more details.

**Comment by tmakatos** [comment]
After fixing the BAR4/5 problem I hit the following error:
```
qemu-system-x86_64: -device vfio-user-pci,socket=/var/run/muser/domain/muser0/8/cntrl: vfio VFIO user </var/run/muser/domain/muser0/8/cntrl>: Failed to set up TRIGGER eventfd signaling for interrupt ERR-0: VFIO2
...
/root/src/qemu/hw/vfio/pci.c:591:vfio_msix_vector_release: Object 0x565048818950 is not an instance of type vfio-pci
./orcl.sh: line 3: 225891 Aborted
```

The first message is a warning, I debugged this a bit and it seems to fail when libvfio-user validates the IRQ:
```
250     // Ensure irq_set's start and count are within bounds.
251     if ((irq_set->start >= vfu_ctx->irq_count[irq_set->index]) ||
252         (irq_set->start + irq_set->count > vfu_ctx->irq_count[irq_set->index])) {
253         vfu_log(vfu_ctx, LOG_DEBUG, "bad IRQ start/count\n");
254         return -EINVAL;
...
(gdb) p irq_set->start
$10 = 0
(gdb) p irq_set->index
$11 = 3
(gdb) p vfu_ctx->irq_count[irq_set->index]
$12 = 0
(gdb) p irq_set->count
$13 = 1
```
I'll continue looking into it to see what's wrong.

Regarding the assertion later on, most likely it's related to the IRQ warning earlier on.

**Comment by tmakatos** [comment]
I've hacked SPDK and QEMU (https://github.com/tmakatos/spdk/tree/vfio-user and https://github.com/tmakatos/qemu/tree/vfio-user-integration) and the VM boots but it fails to probe the NVMe controller. We still need to fix the FD passing issue, and look at the interrupts problem.

**Comment by tmakatos** [comment]
@swapnili is looking at fixing mpqemu to pass file descriptors for DMA regions.

**Comment by tmakatos** [comment]
With a few hacks we've got it working (https://libvfio-user.slack.com/archives/C01AFGCSPTR/p1608305848234000?thread_ts=1608223042.228100&cid=C01AFGCSPTR): SPDK now works with mpqemu.
