### ISSUE TITLE
adapt vfio-user to v6

### ISSUE THREAD

**Issue by tmakatos** [nutanix/libvfio-user#72]
After v6 has been reviewed and accepted (https://lists.gnu.org/archive/html/qemu-devel/2020-11/msg02458.html) we need to incorporate the relevant changes.

**Comment by jlevon** [comment]
I've got changes for the VFIO_USER_VERSION part of this

**Comment by tmakatos** [comment]
I think we've applied all the changes anyway, let's close this.
