### ISSUE TITLE
Support other+extended PCI capabilities e.g Advanced Error Reporting(AER)

### ISSUE THREAD

**Issue by swapnili** [nutanix/libvfio-user#87]
Today device can provide capabilities using following API,
`vfu_pci_setup_caps(vfu_ctx_t *vfu_ctx, vfu_cap_t **caps, int nr_caps)`
For device implementation convenience vfu_cap_t is defined in libvfio-user.h

We need to investigate unsupported capabilities and revisit the API to have a way to support them.

**Comment by jlevon** [comment]
Actually, this bug is essentially complete now. Actual AER support might come via #179
